version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: paymentsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./payment-service/db-init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" 

  payment-service:
    build: ./payment-service
    env_file:
      - ./payment-service/.env.example
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3001:3001"

  notification-service:
    build: ./notification-service
    env_file:
      - ./notification-service/.env.example
    depends_on:
      - rabbitmq
    ports:
      - "3002:3002"

volumes:
  postgres-data:
